apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: documind-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: documind-secret-store
    kind: ClusterSecretStore
  target:
    name: documind-secrets
    creationPolicy: Owner
  data:
    - secretKey: DOCUMIND_ADMIN_API_KEY
      remoteRef:
        key: DOCUMIND_ADMIN_API_KEY
    - secretKey: DOCUMIND_JWT_SECRET_KEY
      remoteRef:
        key: DOCUMIND_JWT_SECRET_KEY
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: POSTGRES_PASSWORD
